services:
  nb-flix-database:
    image: 'bitnami/postgresql'
    ports:
      - 5433:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=nbflix
    volumes:
      - postgres-data:/bitnami/postgresql
    networks:
      - nbflix-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d nbflix"]
      interval: 5s
      timeout: 5s
      retries: 5

  nb-flix-cache:
    image: 'redis:7-alpine'
    networks:
      - nbflix-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  nb-flix-backend:
    build:
      context: .
    ports:
      - 3333:3333
    container_name: "nb-flix-backend"
    environment:
      - REDIS_URL=redis://nb-flix-cache:6379
      - DFINDEXER_URL=http://host.docker.internal:7006
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      nb-flix-database:
        condition: service_healthy
      nb-flix-cache:
        condition: service_healthy
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "Running Prisma migrations..."
        npx prisma migrate deploy --schema=./prisma/schema.prisma # migrate deploy é não-interativo e ideal para produção/startup
        echo "Migrations applied. Starting application..."
        exec node dist/server.js # Inicia sua aplicação Fastify
    networks:
      - nbflix-network

volumes:
  postgres-data:

networks:
  nbflix-network:
    name: nbflix-network
    driver: bridge
    external: true
